name: AUR auto update

on:
  schedule:
    - cron: '53 7 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  update:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
      - uses: arch4edu/cactus/actions/upgrade-archlinux@main
        id: init

      - name: Install runtime dependencies
        run: pacman -S --noconfirm --needed base-devel git jq nvchecker pacman-contrib openssh python-packaging

      - uses: actions/checkout@master

      - name: Set up nvchecker cache
        uses: actions/cache@master
        with:
          path: cache
          key: nvchecker-${{ steps.init.outputs.time }}
          restore-keys: nvchecker-

      - name: Apply configurations
        run: |
          echo "${{ secrets.SSH_KEY }}" | install -Dm400 /dev/stdin /root/.ssh/aur
          cp ssh_config /root/.ssh/config
          useradd makepkg
          git config --global user.name 'Auto update bot'
          git config --global user.email 'auto-update-bot@jingbei.li'

      - name: Run nvchecker
        run: |
          mkdir -p cache
          sed "s/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN}}/" -i keyfile.toml
          sed "s/^#keyfile/keyfile/" -i nvchecker.toml
          set -o pipefail
          nvchecker --logger both -c nvchecker.toml | tee nvchecker.log

      - name: Update AUR
        run: |
          grep '"event": "updated"' nvchecker.log | while read line
          do
            pkgbase=$(echo $line | jq -r '.name')
            newver=$(echo $line | jq -r '.version')
            [ -f update-scripts/${pkgbase}.sh ] && script=${pkgbase}.sh || script=default.sh
            sh -ex update-scripts/${script} ${pkgbase} ${newver} && nvtake -c nvchecker.toml ${pkgbase} || echo "::error Failed to update ${pkgbase}."
          done
